In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv('IMDB Dataset.csv')

In [3]:
df

review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. <br /><br />The...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[50000 rows x 2 columns]

In [4]:
df=df.iloc[:10000]

In [5]:
df

review sentiment
0     One of the other reviewers has mentioned that ...  positive
1     A wonderful little production. <br /><br />The...  positive
2     I thought this was a wonderful way to spend ti...  positive
3     Basically there's a family where a little boy ...  negative
4     Petter Mattei's "Love in the Time of Money" is...  positive
...                                                 ...       ...
9995  Fun, entertaining movie about WWII German spy ...  positive
9996  Give me a break. How can anyone say that this ...  negative
9997  This movie is a bad movie. But after watching ...  negative
9998  This is a movie that was probably made to ente...  negative
9999  Smashing film about film-making. Shows the int...  positive

[10000 rows x 2 columns]

In [6]:
df['sentiment'].value_counts()

positive    5028
negative    4972
Name: sentiment, dtype: int64

In [7]:
df['review'][1]

'A wonderful little production. <br /><br />The filming technique is very unassuming- very old-time-BBC fashion and gives a comforting, and sometimes discomforting, sense of realism to the entire piece. <br /><br />The actors are extremely well chosen- Michael Sheen not only "has got all the polari" but he has all the voices down pat too! You can truly see the seamless editing guided by the references to Williams\' diary entries, not only is it well worth the watching but it is a terrificly written and performed piece. A masterful production about one of the great master\'s of comedy and his life. <br /><br />The realism really comes home with the little things: the fantasy of the guard which, rather than use the traditional \'dream\' techniques remains solid then disappears. It plays on our knowledge and our senses, particularly with the scenes concerning Orton and Halliwell and the sets (particularly of their flat with Halliwell\'s murals decorating every surface) are terribly well d

In [8]:
df.duplicated().sum()

17

In [9]:
df.drop_duplicates(inplace=True)

C:\Users\Soham\AppData\Local\Temp\ipykernel_10572\3006716147.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop_duplicates(inplace=True)


In [10]:
df

review sentiment
0     One of the other reviewers has mentioned that ...  positive
1     A wonderful little production. <br /><br />The...  positive
2     I thought this was a wonderful way to spend ti...  positive
3     Basically there's a family where a little boy ...  negative
4     Petter Mattei's "Love in the Time of Money" is...  positive
...                                                 ...       ...
9995  Fun, entertaining movie about WWII German spy ...  positive
9996  Give me a break. How can anyone say that this ...  negative
9997  This movie is a bad movie. But after watching ...  negative
9998  This is a movie that was probably made to ente...  negative
9999  Smashing film about film-making. Shows the int...  positive

[9983 rows x 2 columns]

In [11]:
df.duplicated().sum()

0

In [12]:
import re
def remove_tags(text):
    cleaned_text=re.sub(re.compile('<.*?>'),'',text)
    return cleaned_text

In [13]:
df['review']=df['review'].apply(remove_tags)

C:\Users\Soham\AppData\Local\Temp\ipykernel_10572\2928534252.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review']=df['review'].apply(remove_tags)


In [14]:
df

review sentiment
0     One of the other reviewers has mentioned that ...  positive
1     A wonderful little production. The filming tec...  positive
2     I thought this was a wonderful way to spend ti...  positive
3     Basically there's a family where a little boy ...  negative
4     Petter Mattei's "Love in the Time of Money" is...  positive
...                                                 ...       ...
9995  Fun, entertaining movie about WWII German spy ...  positive
9996  Give me a break. How can anyone say that this ...  negative
9997  This movie is a bad movie. But after watching ...  negative
9998  This is a movie that was probably made to ente...  negative
9999  Smashing film about film-making. Shows the int...  positive

[9983 rows x 2 columns]

In [15]:
df['review'][1]

'A wonderful little production. The filming technique is very unassuming- very old-time-BBC fashion and gives a comforting, and sometimes discomforting, sense of realism to the entire piece. The actors are extremely well chosen- Michael Sheen not only "has got all the polari" but he has all the voices down pat too! You can truly see the seamless editing guided by the references to Williams\' diary entries, not only is it well worth the watching but it is a terrificly written and performed piece. A masterful production about one of the great master\'s of comedy and his life. The realism really comes home with the little things: the fantasy of the guard which, rather than use the traditional \'dream\' techniques remains solid then disappears. It plays on our knowledge and our senses, particularly with the scenes concerning Orton and Halliwell and the sets (particularly of their flat with Halliwell\'s murals decorating every surface) are terribly well done.'

In [16]:
df['review']=df['review'].apply(lambda x:x.lower())

C:\Users\Soham\AppData\Local\Temp\ipykernel_10572\2697927567.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review']=df['review'].apply(lambda x:x.lower())


In [17]:
df

review sentiment
0     one of the other reviewers has mentioned that ...  positive
1     a wonderful little production. the filming tec...  positive
2     i thought this was a wonderful way to spend ti...  positive
3     basically there's a family where a little boy ...  negative
4     petter mattei's "love in the time of money" is...  positive
...                                                 ...       ...
9995  fun, entertaining movie about wwii german spy ...  positive
9996  give me a break. how can anyone say that this ...  negative
9997  this movie is a bad movie. but after watching ...  negative
9998  this is a movie that was probably made to ente...  negative
9999  smashing film about film-making. shows the int...  positive

[9983 rows x 2 columns]

In [18]:
from nltk.corpus import stopwords

In [19]:
stopwords.words('english')

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [20]:
len(stopwords.words('english'))

179

In [21]:
sw_list=stopwords.words('english')
df['review']=df['review'].apply(lambda x:[item for item in x.split() if item not in sw_list]).apply(lambda x:' '.join(x))

C:\Users\Soham\AppData\Local\Temp\ipykernel_10572\2475415355.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review']=df['review'].apply(lambda x:[item for item in x.split() if item not in sw_list]).apply(lambda x:' '.join(x))


In [22]:
df['review'][1]

'wonderful little production. filming technique unassuming- old-time-bbc fashion gives comforting, sometimes discomforting, sense realism entire piece. actors extremely well chosen- michael sheen "has got polari" voices pat too! truly see seamless editing guided references williams\' diary entries, well worth watching terrificly written performed piece. masterful production one great master\'s comedy life. realism really comes home little things: fantasy guard which, rather use traditional \'dream\' techniques remains solid disappears. plays knowledge senses, particularly scenes concerning orton halliwell sets (particularly flat halliwell\'s murals decorating every surface) terribly well done.'

In [23]:
x=df['review']
y=df['sentiment']

In [24]:
x

0       one reviewers mentioned watching 1 oz episode ...
1       wonderful little production. filming technique...
2       thought wonderful way spend time hot summer we...
3       basically there's family little boy (jake) thi...
4       petter mattei's "love time money" visually stu...
                              ...                        
9995    fun, entertaining movie wwii german spy (julie...
9996    give break. anyone say "good hockey movie"? kn...
9997    movie bad movie. watching endless series bad h...
9998    movie probably made entertain middle school, e...
9999    smashing film film-making. shows intense stran...
Name: review, Length: 9983, dtype: object

In [25]:
y

0       positive
1       positive
2       positive
3       negative
4       positive
          ...   
9995    positive
9996    negative
9997    negative
9998    negative
9999    positive
Name: sentiment, Length: 9983, dtype: object

In [26]:
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()
y=encoder.fit_transform(y)

In [27]:
y.shape

(9983,)

In [28]:
from sklearn.model_selection import train_test_split

In [29]:
X_train,X_test,Y_train,Y_test=train_test_split(x,y,test_size=0.2,random_state=1)

In [30]:
X_train

6713    i've waiting superhero movie like long time. "...
1178    movie excellent acted, excellent directed over...
4707    movie makes want throw every time see it. take...
6772    first saw movie elementary school, back 1960s....
7461    show made persons iq lower 80. jokes show lame...
                              ...                        
2895    excellent episode movie ala pulp fiction. 7 da...
7823    first off, give idea taste movies...2007 comed...
905     well begin story?? went movie tonight friends ...
5195    lot horror fans seem love scarecrows, popular ...
235     reese witherspoon first outing big screen memo...
Name: review, Length: 7986, dtype: object

In [31]:
X_train.shape

(7986,)

In [32]:
X_test.shape

(1997,)

# Using Bag of Words

In [33]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer()
X_train_bow = cv.fit_transform(X_train).toarray()
X_test_bow = cv.transform(X_test).toarray()

In [34]:
X_train_bow

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [35]:
X_train_bow.shape

(7986, 48282)

In [36]:
from sklearn.naive_bayes import GaussianNB

In [37]:
gnb=GaussianNB()

gnb.fit(X_train_bow,Y_train)

GaussianNB()

In [38]:
y_pred=gnb.predict(X_test_bow)

In [39]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [40]:
accuracy_score(Y_test,y_pred)

0.6324486730095142

In [41]:
confusion_matrix(Y_test,y_pred)

array([[717, 235],
       [499, 546]], dtype=int64)

In [42]:
from sklearn.ensemble import RandomForestClassifier

In [43]:
rfc=RandomForestClassifier(n_estimators=200,max_depth=None)

In [44]:
rfc.fit(X_train_bow,Y_train)

RandomForestClassifier(n_estimators=200)

In [45]:
y_pred2=rfc.predict(X_test_bow)

In [46]:
accuracy_score(Y_test,y_pred2)

0.8647971957936905

In [47]:
test_input=['what a great movie']
test_input=cv.transform(test_input).toarray()
rfc.predict(test_input)

array([1])

In [48]:
cv2=CountVectorizer(max_features=5000)

X_train_bow=cv2.fit_transform(X_train).toarray()
X_test_bow=cv2.transform(X_test).toarray()

In [49]:
rfc2=RandomForestClassifier(n_estimators=300,max_depth=None)
rfc2.fit(X_train_bow,Y_train)

RandomForestClassifier(n_estimators=300)

In [50]:
y_pred3=rfc2.predict(X_test_bow)

In [51]:
accuracy_score(Y_test,y_pred3)

0.8482724086129194

In [52]:
test_input=['what a bad movie']
test_input=cv2.transform(test_input).toarray()
rfc2.predict(test_input)

array([0])

# Using Tfidf

In [54]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer()

In [55]:
X_train_tfidf=tfidf.fit_transform(X_train).toarray()
X_test_tfidf=tfidf.transform(X_test).toarray()

In [56]:
rfc.fit(X_train_tfidf,Y_train)

RandomForestClassifier(n_estimators=200)

In [57]:
y_pred=rfc.predict(X_test_tfidf)

In [58]:
accuracy_score(Y_test,y_pred)

0.8522784176264396

In [59]:
test_input=['what a bad movie']
test_input=cv2.transform(test_input).toarray()
rfc2.predict(test_input)

array([0])

In [60]:
test_input=['what a beautiful movie']
test_input=cv2.transform(test_input).toarray()
rfc2.predict(test_input)

array([1])

# Using Word2Vec

In [67]:
from nltk import word_tokenize,sent_tokenize
from gensim.utils import simple_preprocess
import gensim

In [64]:
story=[]

for doc in df['review']:
    raw_sent=sent_tokenize(doc)
    for sent in raw_sent:
        story.append(simple_preprocess(sent))

In [66]:
len(story)

105773

In [68]:
model=gensim.models.Word2Vec(window=10,min_count=2)

In [69]:
model.build_vocab(story)

In [70]:
model.train(story,total_examples=model.corpus_count,epochs=model.epochs)

(5876458, 6212140)

In [71]:
len(model.wv.index_to_key)

31845

In [72]:
model.wv.index_to_key

['movie',
 'film',
 'one',
 'like',
 'good',
 'it',
 'the',
 'would',
 'time',
 'even',
 'story',
 'see',
 'really',
 'well',
 'much',
 'get',
 'bad',
 'great',
 'people',
 'first',
 'also',
 'made',
 'make',
 'way',
 'movies',
 'could',
 'think',
 'characters',
 'watch',
 'character',
 'films',
 'that',
 'never',
 'little',
 'show',
 'seen',
 'many',
 'two',
 'love',
 'acting',
 'plot',
 'best',
 'know',
 'life',
 'this',
 'ever',
 'better',
 'man',
 'there',
 'still',
 'say',
 'scene',
 'end',
 'and',
 'scenes',
 'something',
 'go',
 'real',
 'back',
 'watching',
 'director',
 'actors',
 'years',
 'thing',
 'though',
 've',
 'work',
 'look',
 'funny',
 'actually',
 'old',
 'nothing',
 'going',
 'makes',
 'new',
 'lot',
 'another',
 'all',
 'every',
 'find',
 'pretty',
 'things',
 'part',
 'can',
 'he',
 'us',
 'world',
 'horror',
 'around',
 'want',
 'big',
 'quite',
 'cast',
 'long',
 'young',
 'enough',
 'in',
 'take',
 'seems',
 'got',
 'must',
 'however',
 'may',
 'thought',
 'fa

In [73]:
def document_vector(doc):
    doc=[word for word in doc.split() if word in model.wv.index_to_key]
    return np.mean(model.wv[doc],axis=0)

In [75]:
document_vector(df['review'][0])

array([-0.19173099,  0.4940438 ,  0.21294843,  0.23143268, -0.06896431,
       -0.6029096 ,  0.2165258 ,  0.9562977 , -0.37557063, -0.21290839,
       -0.34684774, -0.4645735 ,  0.02469176,  0.04578961,  0.23125124,
       -0.1347766 , -0.01842628, -0.35009158, -0.06574205, -0.59925616,
        0.04810218,  0.24728139,  0.03929114, -0.30897215, -0.36120507,
        0.00821723, -0.31058878,  0.01748754, -0.32263467,  0.03489245,
        0.3853883 ,  0.01041097,  0.12790853, -0.26578525, -0.15327884,
        0.4782698 ,  0.09809536, -0.43128535, -0.22648203, -0.7405604 ,
        0.12291776, -0.24752752,  0.06336454, -0.07942729,  0.5068192 ,
       -0.15180773, -0.1973463 ,  0.02298698,  0.07478585,  0.30182222,
        0.04502733, -0.3442566 , -0.37062615, -0.14654976, -0.1605349 ,
        0.22699936,  0.21145181,  0.09343546, -0.20572074,  0.07386091,
        0.10658041,  0.09985324,  0.03218361, -0.02783588, -0.45866784,
        0.26388177,  0.02893409,  0.16987757, -0.3878987 ,  0.27

In [78]:
from tqdm import tqdm

In [81]:
x=[]
for doc in tqdm(df['review'].values):
    x.append(document_vector(doc))

100%|██████████████████████████████████████████████████████████████████████████████| 9983/9983 [04:27<00:00, 37.39it/s]


In [82]:
x=np.array(x)

In [84]:
x[1]

array([-0.06298516,  0.44943744,  0.17173512, -0.03955271, -0.00249747,
       -0.5236607 ,  0.0119345 ,  0.71170586, -0.30078587, -0.17336884,
       -0.5255418 , -0.37809557, -0.13869001,  0.1138113 ,  0.23155226,
       -0.11279979,  0.17417397, -0.6390312 , -0.03708722, -0.95385706,
        0.2958702 ,  0.34376985,  0.2953905 ,  0.00641858, -0.00413718,
        0.22537704, -0.20856456, -0.25085863, -0.4248189 ,  0.043613  ,
        0.65195966,  0.06302954,  0.24579774, -0.3605282 , -0.06494183,
        0.55755687, -0.01789499, -0.26434958, -0.4558042 , -0.7329766 ,
        0.19530575, -0.6176329 , -0.28318933,  0.06748229,  0.3878252 ,
       -0.3110903 , -0.36854607, -0.02314083,  0.18830185,  0.33863208,
        0.18669024, -0.37492457, -0.45857066,  0.04515834, -0.23124218,
        0.06880786,  0.12056866, -0.29910368, -0.52594364,  0.00385002,
       -0.1292602 ,  0.03999748, -0.21653764,  0.11436362, -0.47152022,
        0.5240532 , -0.13485667,  0.23146509, -0.30168188,  0.34

In [86]:
x.shape

(9983, 100)

In [88]:
Y_train

array([1, 1, 0, ..., 0, 0, 1])

In [93]:
y

array([1, 1, 1, ..., 0, 0, 1])

In [97]:
X_train,X_test,Y_train,Y_test=train_test_split(x,y,test_size=0.2,random_state=1)

In [98]:
X_test

array([[-0.21058607,  0.3794891 ,  0.27770275, ..., -0.2795418 ,
        -0.0252429 , -0.13976726],
       [-0.1106414 ,  0.45594308,  0.16613062, ..., -0.21464202,
        -0.1498065 , -0.02556781],
       [-0.03639546,  0.44782797,  0.08881018, ..., -0.09918367,
         0.01277907, -0.27658156],
       ...,
       [-0.14339721,  0.43835133,  0.16058466, ..., -0.24503309,
        -0.1091909 , -0.11261042],
       [-0.23092976,  0.3291635 ,  0.19164167, ..., -0.20136715,
        -0.00211514, -0.1637307 ],
       [ 0.0085674 ,  0.57311416,  0.16805638, ...,  0.01912345,
        -0.0631455 , -0.39029938]], dtype=float32)

In [99]:
rfc.fit(X_train,Y_train)

RandomForestClassifier(n_estimators=200)

In [100]:
y_pred=rfc.predict(X_test)

In [101]:
accuracy_score(Y_test,y_pred)

0.7736604907361042